# Travis CI
language: ruby

sudo: false

rvm:
  - &ruby1 2.3.1
  - &ruby2 2.3.0
  - &ruby3 2.2.5

branches:
  only:
    - master

cache: bundler

before_script:
  - chmod +x .travis/bootstrap
  - chmod +x .travis/branding
  - chmod +x .travis/cibuild

script: .travis/cibuild
